let nheader=`
<div class="menu">
            <section class="menu-menu">
                <nav class="menu-principal">
                    <ul>
                        <li><a href="../index.html">Inicio</a></li>
                        <li><a href="M21.html">M21</a></li>
                        <li><a href="M23.html">M23</a></li>
                        <li><a href="M26.html">M26</a></li>
                        <li><a href="M27.html">M27</a></li>
                        <li><a href="M28.html">M28</a></li>
                        <li><a href="M29.html">M29</a></li>
                        <li><a href="M200.html">M200</a></li>
                        <li><a href="M201.html">M201</a></li>
                        <li><a href="M202.html">M202</a></li>
                        <li><a href="M203.html">M203</a></li>
                        <li><a href="M204.html">M204</a></li>
                        <li><a href="M205.html">M205</a></li>
                        <li><a href="M301.html">M301</a></li>
                        <li><a href="M302.html">M302</a></li>
                        <li><a href="M303.html">M303</a></li>
                        <li><a href="M304.html">M304</a></li>
                        <li><a href="M305.html">M305</a></li>
                        <li><a href="M306.html">M306</a></li>
                        <li><a href="M307.html">M307</a></li>
                        <li><a href="M308.html">M308</a></li>
                        <li><a href="M309.html">M309</a></li>
                        <li><a href="M310.html">M310</a></li>
                        <li><a href="M311.html">M311</a></li>
                        <li><a href="M312.html">M312</a></li>
                        <li><a href="M313.html">M313</a></li>
                        <li><a href="M314.html">M314</a></li>
                        <li><a href="M315.html">M315</a></li>
                        <li><a href="M316.html">M316</a></li>
                        <li><a href="M317.html">M317</a></li>
                        <li><a href="M318.html">M318</a></li>
                        <li><a href="M319.html">M319</a></li>
                        <li><a href="M320.html">M320</a></li>
                        <li><a href="M321.html">M321</a></li>
                        <li><a href="M322.html">M322</a></li>
                        <li><a href="M323.html">M323</a></li>
                        <li><a href="M324.html">M324</a></li>
                        <li><a href="M325.html">M325</a></li>
                        <li><a href="M326.html">M326</a></li>
                        <li><a href="M401.html">M401</a></li>
                        <li><a href="M402.html">M402</a></li>
                        <li><a href="M403.html">M403</a></li>
                        <li><a href="M501.html">M501</a></li>
                        <li><a href="M502.html">M502</a></li>
                        <li><a href="M503.html">M503</a></li>
                        <li><a href="M504.html">M504</a></li>
                        <li><a href="M505.html">M505</a></li>
                        <li><a href="M506.html">M506</a></li>
                        <li><a href="M600.html">M600</a></li>
                        <li><a href="M601.html">M601</a></li>
                        <li><a href="M602.html">M602</a></li>
                        <li><a href="M603.html">M603</a></li>
                        <li><a href="M604.html">M604</a></li>
                        <li><a href="M605.html">M605</a></li>
                        <li><a href="M606.html">M606</a></li>
                        <li><a href="M607.html">M607</a></li>
                        <li><a href="M611.html">M611</a></li>
                        <li><a href="M612.html">M612</a></li>
                        <li><a href="M613.html">M613</a></li>
                        <li><a href="M614.html">M614</a></li>
                        <li><a href="M615.html">M615</a></li>
                        <li><a href="M616.html">M616</a></li>
                        <li><a href="M617.html">M617</a></li>
                        <li><a href="M618.html">M618</a></li>
                        <li><a href="M619.html">M619</a></li>
                        <li><a href="M620.html">M620</a></li>
                        <li><a href="M621.html">M621</a></li>
                        <li><a href="M622.html">M622</a></li>
                        <li><a href="M623.html">M623</a></li>
                        <li><a href="M624.html">M624</a></li>
                        <li><a href="M625.html">M625</a></li>
                        <li><a href="M626.html">M626</a></li>
                        <li><a href="M701.html">M701</a></li>
                        <li><a href="M702.html">M702</a></li>
                        <li><a href="M703.html">M703</a></li>
                        <li><a href="M704.html">M704</a></li>
                        <li><a href="M705.html">M705</a></li>
                        <li><a href="M706.html">M706</a></li>
                        <li><a href="M707.html">M707</a></li>
                        <li><a href="M708.html">M708</a></li>
                        <li><a href="M709.html">M709</a></li>
                        <li><a href="M710.html">M710</a></li>
                        <li><a href="MIG-IZQ.html">MIG-IZQ</a></li>
	                    <li><a href="MIG-DER.html">MIG-DER</a></li>
                    </ul>
                </nav>
            </section>
            </div>
`
document.querySelector("header").innerHTML=nheader

let nfooter= `Mx &copy; 2023`
document.querySelector("footer").innerHTML=nfooter

let nh2= `INYECCIÓN`
document.querySelector("h2").innerHTML=nh2